# Generated by Django 2.0.1 on 2018-01-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_links_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='hoboprinter', max_length=50),
        ),
    ]
