# Generated by Django 2.0.1 on 2018-01-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180111_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Callar', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='twin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
