# Generated by Django 2.0.1 on 2018-01-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180111_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Thin Gap', max_length=50),
        ),
        migrations.RemoveField(
            model_name='product',
            name='twin',
        ),
        migrations.AddField(
            model_name='product',
            name='twin',
            field=models.ManyToManyField(blank=True, to='core.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='core.tags'),
        ),
    ]
