# Generated by Django 2.0.1 on 2018-01-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180122_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverts',
            name='advert_text',
            field=models.CharField(default='Learn more', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Bit Moment', max_length=50),
        ),
    ]
