# Generated by Django 2.0.1 on 2018-01-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180122_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='advert_text',
            field=models.CharField(default='learn more', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Vortex Ship', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='twin',
            field=models.ManyToManyField(blank=True, null=True, to='core.product'),
        ),
    ]
