# Generated by Django 2.0.1 on 2018-01-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180124_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverts',
            name='advert_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='monthly_revenue',
            field=models.IntegerField(default=0, help_text="Product's Current Monthly Revenue in USD. Enter '0' if product is in development phase."),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Reavling', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pitch',
            field=models.TextField(blank=True, default='Our revolutionary product will change the world', help_text='Product Pitch in less than 280 character', max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(help_text='Features your website offers.', to='core.tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='twin',
            field=models.ManyToManyField(blank=True, help_text='Websites which are very similar to your website.', to='core.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='website',
            field=models.URLField(help_text='Your Landing page URL', max_length=1000),
        ),
    ]
