# Generated by Django 2.0.1 on 2018-01-24 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180124_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverts',
            name='advert_end',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adverts',
            name='advert_lifespan',
            field=models.IntegerField(choices=[(1, 1), (7, 7), (28, 28)], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Rings of Bong', max_length=50),
        ),
    ]
