# Generated by Django 2.0.1 on 2018-01-24 14:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180124_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='ad_words',
            field=models.CharField(blank=True, default=0, help_text='Your advertisment text in 128 characters', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='advert_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='advert_lifespan',
            field=models.IntegerField(choices=[(1, '1 Day'), (7, '7 Days'), (28, '28 Days')], default=1, help_text='Number of days you want the advert to be live'),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='advert_text',
            field=models.CharField(default='learn more', help_text='Button text to redirect to your link', max_length=20),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', help_text='Image size MUST be 350×250', null=True, upload_to=core.models.upload_location, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='max_clicks',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Glowing Bulb', max_length=50),
        ),
    ]
