# Generated by Django 2.0.1 on 2018-01-25 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180124_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(default='Glowing Bulb', max_length=50)),
                ('catagory_pitch', models.TextField(blank=True, default='Our revolutionary product will change the world', help_text='Catagory Detail', max_length=280, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Rings of Bong', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catagory', to='core.product_catagory'),
        ),
    ]
