# Generated by Django 2.0.1 on 2018-01-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180125_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_catagory',
            name='popular',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Reavling', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='catagory_name',
            field=models.CharField(default='BlueSkin', max_length=50),
        ),
    ]
