# Generated by Django 2.0.1 on 2018-01-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180126_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_catagory',
            name='UserBase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Stick ship', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='catagory_name',
            field=models.CharField(default='Spinning Floor', max_length=50),
        ),
    ]
