# Generated by Django 2.0.1 on 2018-01-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180127_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_catagory',
            name='avg_revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_catagory',
            name='high_revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_catagory',
            name='total_revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Measurant', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='catagory_name',
            field=models.CharField(default='Vortex Ship', max_length=50),
        ),
    ]
