# Generated by Django 2.0.1 on 2018-01-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180127_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adverts',
            options={'verbose_name': 'Advert', 'verbose_name_plural': 'Advertisments'},
        ),
        migrations.AlterModelOptions(
            name='email_list',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Email List', 'verbose_name_plural': 'Email Lists'},
        ),
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='product_catagory',
            options={'verbose_name': 'Product Catagory', 'verbose_name_plural': 'Product Catagories'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Reavling', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='catagory_name',
            field=models.CharField(default='Rock anne Role', max_length=50),
        ),
    ]
