# Generated by Django 2.0.1 on 2018-01-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20180127_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Thin Gap', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='UserBase',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='avg_revenue',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='catagory_name',
            field=models.CharField(default='Eurika', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='high_revenue',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='total_revenue',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
