# Generated by Django 2.0.1 on 2018-01-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20180127_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='revenue_source',
            field=models.CharField(choices=[('From Internet, unverified', 'internet, unverified'), ('From Internet, Admin Verified', 'internet, admin verified'), ('Maker Verified', 'maker verified'), ('Not for Public Viewing', 'Not for public viewing')], default='From Internet, unverified', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Eurika', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='catagory_name',
            field=models.CharField(default='Wild flips', max_length=50),
        ),
    ]
