# Generated by Django 2.0.1 on 2018-01-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20180129_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='revenue_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('------', '------'), ('Advertisments', 'Ads'), ('Subscription', 'subscription'), ('One time Payment', 'entry fees'), ('Product sales', 'sales')], default='------', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='revenue_info_source',
            field=models.CharField(choices=[('From Internet, unverified', 'internet, unverified'), ('From Internet, Admin Verified', 'internet, admin verified'), ('Maker Verified', 'maker verified'), ('Not for Public Viewing', 'Not for public viewing')], default='From Internet, unverified', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Thin Gap', max_length=50),
        ),
        migrations.RemoveField(
            model_name='product',
            name='revenue_source',
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='catagory_name',
            field=models.CharField(default='Stick ship', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='revenue_source',
            field=models.ManyToManyField(help_text='How do you get the revenue? please choose atleast one', to='core.revenue_source'),
        ),
    ]
