# Generated by Django 2.0.1 on 2018-01-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20180131_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Rings of Bong', max_length=50),
        ),
    ]
