# Generated by Django 2.0.1 on 2018-01-31 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20180131_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='anon_user_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=200)),
                ('contact_type', models.CharField(choices=[('Twitter', 'twitter'), ('e-mail', 'email')], default='Twitter', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Glowing Bulb', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='catagory_name',
            field=models.CharField(default='Eurika', max_length=50),
        ),
        migrations.AddField(
            model_name='anon_user_detail',
            name='connected_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_connected', to='core.product'),
        ),
    ]
