# Generated by Django 2.0.1 on 2018-02-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20180201_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='anon_user_detail',
            name='new_string',
            field=models.CharField(default='o', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='BlueSkin', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='catagory_name',
            field=models.CharField(default='Bit Moment', max_length=50),
        ),
    ]
