# Generated by Django 2.0.1 on 2018-02-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20180202_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anon_user_detail',
            name='new_string',
        ),
        migrations.AlterField(
            model_name='adverts',
            name='advert_status',
            field=models.CharField(choices=[('Unpaid', 'unpaid'), ('Paid', 'paid'), ('Displaying', 'displaying'), ('Completed', 'completed')], default='Unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='email_list',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='hoboprinter', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='catagory_name',
            field=models.CharField(default='BlueSkin', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
