# Generated by Django 2.0.1 on 2018-02-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20180202_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anon_user_detail',
            name='new_string',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Rock anne Role', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='catagory_name',
            field=models.CharField(default='Thin Gap', max_length=50),
        ),
    ]
