# Generated by Django 2.0.1 on 2018-02-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20180215_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Eurika', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='catagory_name',
            field=models.CharField(default='Cube box', max_length=50),
        ),
    ]
