# Generated by Django 2.0.1 on 2018-02-02 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20180202_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anon_user_detail',
            name='new_string_uuid',
            field=models.CharField(default=uuid.uuid1, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Wild flips', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='catagory_name',
            field=models.CharField(default='Stick ship', max_length=50),
        ),
    ]
