# Generated by Django 2.0.1 on 2018-03-22 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0036_auto_20180322_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('detail', models.TextField(blank=True, default='Product details', help_text='Product Pitch in less than 280 character', max_length=280, null=True)),
                ('link', models.URLField(help_text='URL', max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Phone Smith', max_length=50),
        ),
    ]
