# Generated by Django 2.0.1 on 2018-02-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20180202_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anon_user_detail',
            name='new_string_uuid',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Trackin', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='catagory_name',
            field=models.CharField(default='Trackin', max_length=50),
        ),
    ]
