# Generated by Django 2.0.1 on 2018-03-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20180322_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_items',
            name='revenue_source',
            field=models.CharField(choices=[('Advert', 'ad'), ('Royalty', 'royalty'), ('Marketplace', 'marketplace')], default='Advert', max_length=100),
        ),
        migrations.AddField(
            model_name='list_items',
            name='suitable_for',
            field=models.CharField(choices=[('Music Creator', 'music'), ('Painter', 'painter'), ('Video creator', 'video creator'), ('Internet Entrepreneur', 'internet ent')], default='Music Creator', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Spinning Floor', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='catagory_name',
            field=models.CharField(default='hoboprinter', max_length=50),
        ),
    ]
