# Generated by Django 2.0.1 on 2018-02-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20180208_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='advert_status',
            field=models.CharField(choices=[('Unpaid', 'unpaid'), ('Paid', 'paid'), ('Displaying', 'displaying'), ('Completed', 'completed')], default='Unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='email_list',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Glowing Bulb', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='catagory_name',
            field=models.CharField(default='Spinning Floor', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_catagory',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
